### ISSUE TITLE
write_gpickle error

### ISSUE THREAD

**Issue by pgonzale60** [DRL/syngraph#5]
Hi Alex,

My version of syngraph is that of 3a4a6fa commit. I'm getting the following error after issuing the command `python ../syngraph build -d synInput/ -m -o test`.

```
[+] Creating Syngraph from markers ...
[+] Show Syngraph metrics ...
[=] ====================================
[=] Taxa = 14
[=] Nodes (Markers) = 3131
[=] Nodes (Markers) shared by > 1 taxon = 3130
[=] Nodes (Markers) shared by all taxa = 1036
[=] Distinct Edges (Adjacencies) = 20439
[=] Subgraphs (connected components) = 1
[=] ====================================
[+] Save Syngraph to file ...
Traceback (most recent call last):
  File "/Users/pg17/Programs/syngraph/fourteen_nemas_busco5.2.2_odb10/../syngraph", line 7, in <module>
    main()
  File "/Users/pg17/Programs/syngraph/cli/interface.py", line 39, in main
    build.main(run_params)
  File "/Users/pg17/Programs/syngraph/cli/build.py", line 61, in main
    graph_file = syngraph.save(parameterObj, check_consistency=True, with_ancestors=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pg17/Programs/syngraph/source/syngraph.py", line 863, in save
    nx.write_gpickle(self, graph_file)
    ^^^^^^^^^^^^^^^^
AttributeError: module 'networkx' has no attribute 'write_gpickle'
```

This is probably due to version differences. Please find attached [my conda environment](https://github.com/DRL/syngraph/files/11982619/pg_syngraph_conda_env.txt) for reference. 

Also related, the current `conda install` guidance on the README does not include `matplotlib seaborn` packages on which syngraph currently relies on. Could you add a YAML of the conda environment that works for you so that one can do `conda env create --file environment.yaml`?

Best,
Pablo

**Comment by A-J-F-Mackintosh** [comment]
Hi Pablo,

I am using networkx version 2.4. Pickling an object in this way must be deprecated in later versions.

I have included a yaml file of my conda env (in a folder called yaml). I have also added matplotlib to the list of dependencies in the README, along with networkx=2.4.

I will likely need to go through various dependencies at some point and see what has become deprecated over the last two years, although hopefully the quick fix above will work for now.

Best,

Alex
