### ISSUE TITLE
TypeError: 'method' object is not subscriptable in syngraph.py from_markerObjs

### ISSUE THREAD

**Issue by pgonzale60** [DRL/syngraph#6]
Hi Alex,

I'm struggling to run syngraph in the attached [dataset](https://github.com/DRL/syngraph/files/12094263/fourteen_nemas_synInput.tar.gz). Each TSV file has the four columns specified in the README. I'm running syngraph commit `3a4a6faf1baec064a`. I created a conda environment using `mamba create --name syngraph_t2 -c bioconda -c conda-forge networkx==1.11 pandas docopt tqdm ete3 pygraphviz matplotlib seaborn more-itertools -y`. I'm running the command `python syngraph build -d synInput -m -o fourteen_nemas`.

I get the following error.
```
[+] Creating Syngraph from markers ...
Traceback (most recent call last):
  File "/Users/pg17/Programs/syngraph/syngraph", line 7, in <module>
    main()
  File "/Users/pg17/Programs/syngraph/cli/interface.py", line 39, in main
    build.main(run_params)
  File "/Users/pg17/Programs/syngraph/cli/build.py", line 57, in main
    syngraph.from_markerObjs(markerObjs)
  File "/Users/pg17/Programs/syngraph/source/syngraph.py", line 916, in from_markerObjs
    self.nodes[markerObj.name]['taxa'].add(markerObj.taxon)
TypeError: 'method' object is not subscriptable
```

Do you know how I could overcome this?

Best,
Pablo

**Comment by A-J-F-Mackintosh** [comment]
Hi Pablo,

Did you resolve this? If not, could you try with the latest commit (and with networkx version 2.4).

Thanks for flagging these issues :)

Alex
