### ISSUE TITLE
Example data

### ISSUE THREAD

**Issue by DiegoDolgetta** [DRL/syngraph#9]
Hi Alex,

Would you be able to make an example orthology dataset and an example newick tree available to test your program? I am trying to use it but I believe that my orthology files and input tree may have a slightly different format, causing me some issues.
Thank you in advance for your help!

**Comment by A-J-F-Mackintosh** [comment]
Hi,

Apologies for such a slow reply.

I have added some example data. I hope it helps you identify the problem. If not, just let me know what kind of error you get and then hopefully I can help.

Cheers,

Alex
